# Generated by Django 3.1.2 on 2020-10-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=1, verbose_name='Колонка')),
                ('row', models.IntegerField(verbose_name='Строка')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
            ],
        ),
    ]
